import type { Metadata } from "next";
import "./globals.css";
import {Inter} from 'next/font/google';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const InterFont = Inter({
  subsets: ['latin'],
  weight: ['200','300','400','500','600','700','800','900'],
  variable: '--font-inter',
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased ${InterFont.variable} bg-[#F8FAFC]`}
      >
        {children}
      </body>
    </html>
  );
}
